---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: localhost
  pre_tasks:
    - name: k8s_apikey
      set_fact:
        k8s_apikey: "{{my_k8s_apikey}}"
    - name: k8s_apiurl
      set_fact:
        k8s_apiurl: "{{my_k8s_apiurl}}"
    - name: namespace
      set_fact:
        namespace: "{{namespace}}"
    - name: validate_certs
      set_fact:
        validate_certs: "no"



  roles:
    - check-ns-create-event
