
  - block:
 
    - name: DEBUG -                 🟢 API URL
      debug: 
        var: k8s_apiurl


    - name: DEBUG -                 🟢 API KEY
      debug: 
        var: k8s_apikey

    - name: OCP Login
      shell: |
        oc login --token={{ my_k8s_apikey }} --server={{ my_k8s_apiurl }} --insecure-skip-tls-verify
      ignore_errors: true
      register: EXEC_RESULT
    - name: 🟣  OUTPUT - OCP Login
      debug: 
        var: EXEC_RESULT.stdout_lines
        #verbosity: 1



    - name: Create MYSQL Problem (NEW)
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo " 🚀 Create MYSQL Problem"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo ""
        echo ""

        oc set env deployment ratings -n robot-shop PDO_URL="mysql:host=mysql;dbname=ratings-dev;charset=utf8mb4"
        oc set env deployment load -n robot-shop ERROR=1


        echo ""
        echo ""
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo " ✅ Create MYSQL Problem - DONE"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"


      ignore_errors: true
      register: EXEC_RESULT
    - name: 🟣  OUTPUT - Create MYSQL Problem
      debug: 
        var: EXEC_RESULT.stdout_lines
        #verbosity: 1




